FROM fabric8/fabric8-ui-builder:vff6c6fa

# this dockerfile builds a docker image of the npm install so that we can run the E2E tests quickly from this image
# without having to wait for npm to download the internet first

RUN git clone https://github.com/fabric8io/fabric8-test.git /test
RUN cd /test/ee_tests && npm install && webdriver-manager update --standalone true --versions.chrome 2.29

WORKDIR /test/ee_tests

#ENTRYPOINT ["/test/ee_tests/entrypoint.sh"]
